<?php
return [
    "ENV_DEV"=>env('ENV_DEV'),
    "ENV_LIVE"=>env('ENV_LIVE'),
    "ESEWA_DEV_MERCHANT"=>env('ESEWA_DEV_MERCHANT'),
    "ESEWA_LIVE_MERCHANT"=>env('ESEWA_LIVE_MERCHANT'),
    "PAYMENT_VERIFICATION"=>env('PAYMENT_VERIFICATION')
];